### ISSUE TITLE
2024.1 EAP Support Please 😊

### ISSUE THREAD

**Issue by Mike-E-angelo** [ulex/ZenSharp#52]
I tried the EAP but this extension listed as incompatible. 💥  Any effort you can provide to addressing this would be appreciated. 🙏

**Comment by ulex** [comment]
@Mike-E-angelo the binary compatibiity was broken several times during 2024.1 EAP due to a huge refactoring in the component container, unfortunately. in EAP6 it will be broken again (hopefully for the last time during this release cycle) and I will update the plugin for the EAP6 when it is available. Sorry for the inconvenience.

**Comment by Mike-E-angelo** [comment]
Sounds good to me @ulex.  I am actually OK with delays in the name of refactoring/quality. 😊  Only said as that has been my life for the past two months. 😅

**Comment by Mike-E-angelo** [comment]
Awesome!  Thank you so very much for your efforts @ulex here and over the years.  They and you are greatly appreciated. 🙏😌
