### ISSUE TITLE
Support for R# 2024.2+

### ISSUE THREAD

**Issue by 0x0309** [ulex/ZenSharp#53]

**Comment by ulex** [comment]
Since the introduction of [API Verifier] there is no need to repack the plugin for each major release. There have been no API changes since 2024.1, so the current version will still work in 2024.2. Are you having problems with it?

[API Verifier]: https://blog.jetbrains.com/dotnet/2023/05/26/the-api-verifier/

**Comment by 0x0309** [comment]
Ok, great! Tried upgrading R# now and this plugin works.

I usually check the plugins website first before upgrading R#, and it's not clear on there whether this plugin is compatible with the latest 2024.2 release.
https://plugins.jetbrains.com/plugin/11645-zensharp-auto-completion-plugin/versions
![image](https://github.com/user-attachments/assets/59803a31-2456-4803-b2c8-0a390cbcd1bf)
